latest <- readRDS("~/jsPsych/output/results/id=8&p_id=7bdfd908a80fd2f208d4bc97353347d4ee0e2b53d6dfd4bc005e8d58aaa59ea7&save_id=1&pilot=false&complete=true.rds")
write.csv(fromJSON(latest$results$jspsych), "latestdata.csv")
library(readr)
latestdata <- read_csv("~/jsPsych/latestdata.csv")
View(latestdata)

write.csv(fromJSON(full_RT$results$jspsych), "full_RT.csv")
library(readr)
full_RT <- read_csv("~/jsPsych/full_RT.csv")
View(full_RT)

library(jsonlite) 
write.csv(fromJSON(hej$results$jspsych), "hej.csv")
library(readr)
hej <- read_csv("~/jsPsych/hej.csv")
View(hej)
